spring.datasource.url=jdbc:postgresql://localhost:5432/hibernatedb
spring.datasource.username=postgres
spring.datasource.password=Deepu@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

server.port=8084

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB


# GOOGLE OAUTH2


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# React frontend URL used after Google login
app.frontend-url=${FRONTEND_URL:http://localhost:3003}
